// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1vWET4Jw_xgvcnyg3k1qXX-QfPN9hlOs',
    appId: '1:356268847073:web:f08a825fde22040f3d2ca0',
    messagingSenderId: '356268847073',
    projectId: 'ulearning-app-bloc-provider',
    authDomain: 'ulearning-app-bloc-provider.firebaseapp.com',
    storageBucket: 'ulearning-app-bloc-provider.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXuQEJ1OaFySYdCk3plsn_2HAxXxdCFQY',
    appId: '1:356268847073:android:de73670296cbe3953d2ca0',
    messagingSenderId: '356268847073',
    projectId: 'ulearning-app-bloc-provider',
    storageBucket: 'ulearning-app-bloc-provider.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0g0IfBL694833Nc0hdyTVgkgwakXWTOo',
    appId: '1:356268847073:ios:c23a6e003d573e773d2ca0',
    messagingSenderId: '356268847073',
    projectId: 'ulearning-app-bloc-provider',
    storageBucket: 'ulearning-app-bloc-provider.appspot.com',
    iosBundleId: 'com.example.ulearningAppBlocProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0g0IfBL694833Nc0hdyTVgkgwakXWTOo',
    appId: '1:356268847073:ios:c23a6e003d573e773d2ca0',
    messagingSenderId: '356268847073',
    projectId: 'ulearning-app-bloc-provider',
    storageBucket: 'ulearning-app-bloc-provider.appspot.com',
    iosBundleId: 'com.example.ulearningAppBlocProvider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1vWET4Jw_xgvcnyg3k1qXX-QfPN9hlOs',
    appId: '1:356268847073:web:a9b60791d5cc67a23d2ca0',
    messagingSenderId: '356268847073',
    projectId: 'ulearning-app-bloc-provider',
    authDomain: 'ulearning-app-bloc-provider.firebaseapp.com',
    storageBucket: 'ulearning-app-bloc-provider.appspot.com',
  );

}